DROP TABLE IF EXISTS "public"."rekening";
CREATE TABLE "public"."rekening" (
"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
),
"nama" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
"saldo" numeric(15,2) NOT NULL
)
;

INSERT INTO "public"."rekening" VALUES (1, 'Ali', 10000.00);
INSERT INTO "public"."rekening" VALUES (2, 'Bejo', 10000.00);
INSERT INTO "public"."rekening" VALUES (3, 'Candra', 10000.00);
INSERT INTO "public"."rekening" VALUES (4, 'Dullah', 10000.00);
INSERT INTO "public"."rekening" VALUES (5, 'Eka', 10000.00);
INSERT INTO "public"."rekening" VALUES (6, 'Feri', 10000.00);
INSERT INTO "public"."rekening" VALUES (7, 'Gerardo', 10000.00);
INSERT INTO "public"."rekening" VALUES (8, 'Hariono', 10000.00);
INSERT INTO "public"."rekening" VALUES (9, 'Indra', 10000.00);
INSERT INTO "public"."rekening" VALUES (10, 'Jayus', 10000.00);

CREATE OR REPLACE PROCEDURE "public"."transfer_dana_by_nama"("pengirim" varchar,
"penerima" varchar, "jumlah_transfer" numeric)
AS $BODY$
begin
-- mengurangi jumlah_transfer dari saldo pengirim
update rekening
set saldo = saldo - jumlah_transfer
where nama = pengirim;
-- menambah jumlah_transfer ke saldo penerima
update rekening
set saldo = saldo + jumlah_transfer
where nama = penerima;
commit;
end;$BODY$
LANGUAGE plpgsql

CALL transfer_dana_by_nama('Bejo','Jayus',2000);

SELECT * FROM rekening order by id;

CREATE OR REPLACE PROCEDURE "public"."transfer_dana_by_id"("pengirim" int4,
"penerima" int4, "jumlah_transfer" numeric)
AS $BODY$
begin
-- mengurangi jumlah_transfer dari saldo pengirim
update rekening
set saldo = saldo - jumlah_transfer
where id = pengirim;
-- menambah jumlah_transfer ke saldo penerima
update rekening
set saldo = saldo + jumlah_transfer
where id = penerima;
commit;
end;$BODY$
LANGUAGE plpgsql

CALL transfer_dana_by_id(3,9,4000);

SELECT * FROM rekening order by id;